### ISSUE TITLE
Messy Results

### ISSUE THREAD

**Issue by JEG2** [zweifisch/ob-elixir#6]
I'm getting some junk filled results in Spacemacs on macOS Ventura:

```org
#+begin_src elixir
  21 * 2
#+end_src

#+RESULTS:
: import_file("/var/folders/bl/t34fzq8x091f59cgcvtq2j540000gn/T/babel-3O5x9z/elixir-Vh4j43")[A$<2>[J$<50>iex(5)> import_file("/var/folders/bl/t34fzq8x091f59cgcvtq2j540000gn/T/babel-3O5x9z/elixir-Vh4j43")
: 42[J$<50>iex(6)> 
```

**Comment by icostan** [comment]
Still happening... any updates?

#+BEGIN_SRC elixir :remsh name@node :sname console
Node.self
#+END_SRC

#+RESULTS:
: [A[Jiex(5)> import_file("/tmp/babel-rC9b1e/elixir-XEN0aY")
: :nonode@nohost
: [A[Jiex(6)>

**Comment by zweifisch** [comment]
fixed in 8e5d2f3c7adb0d5acde390264fec94627aa7af31

**Comment by dustinfarris** [comment]
EDIT: nvm, i was not on latest — this is working now!

~~still not working for me on latest master~~

**Expected:**

```elixir
#+begin_src elixir :results code
DateTime.utc_now()
#+end_src

#+RESULTS:
#+begin_src elixir
~U[2025-07-11 17:53:34.394993Z]
#+end_src
```

**Actual:**

```elixir
#+begin_src elixir :results code
DateTime.utc_now()
#+end_src

#+RESULTS:
#+begin_src elixir
[A[A[Jiex(6)> import_file("/var/folders/1r/b8gr_rxs4yq5fjcdhgdprf4r0000gp/T/babel-NmG2Ck/elixir-5bMmDj")
~U[2025-07-11 17:53:34.394993Z]
[A[Jiex(7)> 
#+end_src
```

**Comment by dustinfarris** [comment]
this is working, thank you!
